USE gomarvelfacts;
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO CHARACTERS
Values (501, 'Iron Man', 'When billionaire industrialist Tony Stark dons his sophisticated steel-mesh armor, he becomes a living high-tech weapon - the world\'s greatest fighting machine. Tony has primed his ultra modern creation for waging state of the art campaigns, attaining sonic flight, and defending the greater good! He is the Armored Avenger - driven by a heart that is part machine, but all hero! He is the INVINCIBLE IRON MAN!', 101),
(502, 'Hulk', 'A massive dose of gamma radiation transformed the brilliant but meek scientist Bruce Banner\'s DNA, awakening the hidden, adrenaline-fed hero in his genes... HULK! A hero of few words and incredible strength, the Hulk has long been pursued by those who want to use his immense power for their own purposes, or by those who thought the Jade Giant\'s anger was too dangerous to be controlled. Now, as a member of the Avengers, Hulk helps smash the unimaginable threats that no Hero could face alone, hoping to at least prove to the world that he is the strongest HERO there is!', 102),
(503, 'Thor', 'Nordic legend tells the tale of the son of Odin, the heir to the throne of Asgard - he is THOR, renowned as the mightiest hero of mythology! Thor\'s strength, endurance, and quest for battle are far greater than his Asgardian brethren. The mighty Thor wields an enchanted Uru hammer, Mjolnir, and is master of thunder and lightning.', 103),
(504, 'Captain America', 'During WWII, the patriotic Steve Rogers was offered a place in the military\'s top operation: Rebirth. Injected with an experimental super-serum, Rogers emerged from the treatment with heightened endurance, strength, and reaction time. With extensive training and an indestructible Vibranium shield, Rogers soon became the country\'s ultimate weapon: CAPTAIN AMERICA! Though frozen in ice during a climactic battle toward the end of the war, Rogers was discovered and revived decades later. Now the living legend continues the war against evil in modern times as a member of The Avengers!', 104),
(505, 'Hawk Eye', 'An archer with perfect accuracy and a quiver of trick arrows, Clint Barton\'s wit is usually faster than his lightning-quick reflexes! Though this expert archer doesn\'t always follow the rules, he long ago proved himself an invaluable member of The Avengers as Hawkeye!', 105),
(506, 'Black Widow', 'Natasha Romanoff is the super-spy known as the Black Widow! Trained extensively in the art of espionage and outfitted with state-of-the-art equipment, Black Widow\'s combat skills are virtually unmatched. One of S.H.I.E.L.D\'s most valuable agents, she has carried out numerous black-ops missions and has recently been assigned by Director Nick Fury to keep an eye on the Avengers.', 106),
(507, 'Loki', 'Loki is an evil Asgardian being and wielder of mischief bent on conquering Asgard, enslaving the Earth, and destroying his stepbrother - The Mighty Thor. Loki is a master manipulator and enjoys tricking others into fighting his battles for him. While he may usually prefer to act behind the scenes, he should never be underestimated in one-on-one combat. His knowledge of evil allows him to perform illusions, shape-shift, and hypnotically influence those around him. These abilities, combined with his Asgardian warrior training, make Loki a dangerous foe.', 107),
(508, 'Winter Soldier', 'Bucky Barnes served with honor in WWII alongside his partner and best friend, Captain America. Presumed M.I.A. after a fateful mission toward the end of the war, Bucky had in fact been recovered by enemy agents who subjected him to a series of traumatic metal and physical experiments. Stripped of his identity, Bucky was reborn as the Winter Soldier, a cunning and dangerous covert operative who could be “activated” from cryostasis every decade or so to undertake special missions. Ultimately free of his brainwashing, Bucky now uses his impressive talents to try and atone for the deeds done while under enemy control.', 108),
(509, 'Vision', 'Driven by an extremely lifelike artificial intelligence and possessing a nearly indestructible robotic body, the synthetic android called the Vision has taken his place among Earth\'s Mightiest Heroes, the Avengers! In addition to his surprisingly human personality, the Vision exhibits an impressive compliment of abilities, including flight, complete control over his molecular density and the ability to fire energy blasts from the jewel on his forehead.', 109),
(510, 'Doctor Strange', 'Distinguished neurosurgeon Doctor Stephen Strange\'s self-important worldview was shattered, along with his steady operating hands, in a fateful car accident. Desperate to heal his injuries and pride, Strange sought out a legendary safe known as the Ancient One, becoming a pupil of the mystic arts. Learning that his true worth had always come from within, Strange uncovered his full potential and was chosen to become the Sorcerer Supreme, the world\'s pre-eminent defender against the darkness that lurks beyond.', 110),
(511, 'Black Panther', 'Monarch of the secluded but technologically advanced African nation of Wakanda, King T\'Challa is the Black Panther; a sacred title that must be both inherited & earned by the current Wakandan ruler. Granted superhuman powers by ceremonially consuming a mystical heart-shaped herb, the Black Panther is responsible for defending his people, and the world, from any threats.', 111),
(512, 'Ant-man', 'Former thief Scott Lang once stole an advanced size-altering suit in order to aid his ailing daughter, only to discover that the stolen tech belonged to the world-renowned Dr. Hank Pym. Seeing the heroic potential within him, Dr. Pym allowed Scott to continue using the suit, as well as the identity Pym once battled evil under. As the Astonishing Ant-Man, Scott now handles the jobs “too small” for any other SuperHero.', 112),
(513, 'Wasp', 'Endowed with the amazing ability to shrink in size and fly, Hope Van Dyne is the newest heroine to bear the name Wasp! Along with her partner Scott Lang, the Astonishing Ant-Man, Wasp battles evil on any scale, proving that true heroism comes in even the smallest sizes!', 113),
(514, 'Captain Marvel', 'Former Air Force pilot and intelligence agent Carol Danvers pursued her dream of space exploration as a NASA employee, but her life forever changed when she was accidentally transformed into a human-Kree hybrid with extraordinary powers.', 114),
(515, 'Thanos', 'Physically, Thanos stands head and shoulders above the average human or humanoid, with powerful muscles, a broad face, and a purple-hued skin tone. He often wears a protective suit of armor and his strength is such that he has been physically able to battle—and defeat—the likes of the Hulk.', 115),
(516, 'Spider Man', 'The bite from a radioactive spider granted Peter Parker amazing arachnid-like powers. After losing his beloved Uncle Ben to a burglar, grief- stricken Peter vowed to use his incredible abilities to protect his city as the Amazing Spider-Man. Peter\'s trials taught him an invaluable lesson: with great power, there must also come great responsibility.', 116),
(517, 'Star Lord', 'A headstrong intergalactic adventurer, Peter Quill was taken from his Earthly home at a young age, growing up in outer space alongside the pirate-like Ravagers. As the intrepid Star-Lord, Quill travels the cosmos in his spaceship, the Milano, seeking his fortune. Equipped with a high- tech blaster and a mix-tape of music from home, Star-Lord leads an unlikely team of interstellar misfits – the Guardians of the Galaxy – in their attempts to do a little good, a little bad, a little of both!', 117),
(518, 'Groot', 'The last surviving member of a tree-like alien race, Groot is perhaps one of the most unusual beings in all the cosmos. Though calm and quiet in most instances, he is known to unleash his tremendous strength on any enemy foolish enough to threaten his allies, particularly his long- time partner in crime, Rocket. Though he can only vocalize using the phrase, “I am Groot,” the gentle giant\'s friends are nevertheless able to understand his exact meaning through his subtle inflections.', 118),
(519, 'Gamora', 'Orphaned as a child when the rest of her species was annihilated, Gamora was found and raised by the tyrant Thanos, who conditioned her to become an unparalleled warrior. Weary of the acts she was forced to commit in her would-be father\'s name, Gamora later broke free of her chains. Teaming up with Star-Lord and his motley crew, the “most dangerous woman in the galaxy” now seeks to redeem her past crimes, putting her unparalleled skills to use as a member of the Guardians of the Galaxy.', 119),
(520, 'Rocket Raccoon', 'Though he may look like a common Earth raccoon, the temperamental Rocket is in fact a one-of-a-kind genetically produced being, originally created on the planet Halfworld. This diminutive, tough- talking creature is a master pilot, engineer, marksman, and weapons specialist. Previously a small-time thief along with his partner Groot, Rocket lends his genius and heavy artillery to the Guardians of the Galaxy, unable to resist the call of adventure (and plunder).', 120),
(521, 'Drax the destroyer', 'Fueled by a personal vendetta against those who cost him his family, the rough-edged warrior called Drax the Destroyer has room in his life for little else besides revenge. To this end, the heavily tattooed Drax has long relied upon his proficiency in battle and his razor-sharp blades to do his talking for him. After making a tentative alliance with the Guardians of the Galaxy, the untamed Drax must learn to put the needs of the universe before his own.', 121),
(522, 'Wanda Maximoff', 'Although much of the Scarlet Witch\'s true origins remain elusive to her thanks to manipulations by others, she can still recall her early days as a child with her twin brother Pietro. The two lived on Wundagore Mountain in Eastern Europe, believing themselves born as mutants to a Romani couple named the Maximoffs. Given the name Wanda, she lived for a short time in childish innocence until local troubles involving her parents separated her and her brother from them and forced her to hide her growing powers.', 122),
(523, 'Nick Fury', 'Nick Fury became an elite member of the U.S. intelligence team because of intellect and integrity. He has been trained as a paratrooper, Ranger, demolitions expert and vehicle specialist. Nick Fury keeps his youth by the mysterious Infinity Formula. When the world is in trouble, NICK FURY: AGENT OF S.H.I.E.L.D. is the man who will defend it.', 123),
(524, 'Ultron', 'The robotic creation known as Ultron was initially activated with the best of intentions, but its artificial intelligence evolved too quickly. The evil robot soon figured out that all of humanity and the Avengers in particular would stand in the way of its rise into robotic perfection. Because of this Ultron upgrades its highly advanced form constantly, adapting its near-limitless abilities to match its twisted desire for ever more power and total domination.', 124),
(525, 'Falcon', 'The top of his class at S.H.I.E.L.D., Sam Wilson\'s savvy with experimental technology quickly impressed even Tony Stark. Working as Stark\'s protégé, the eager agent designed a sleek suit of flying armor, complete hard-light holographic wings, and an extensive arsenal that includes explosive “flechettes” and retractable talons. When the call came for Sam to graduate to the Avengers, he didn\'t hesitate — he quickly took to the skies in a streak of red as Falcon!', 125);
